weeks/08_week/mvc/app/models/user_model.py
from database import db

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    date_of_birth = db.Column(db.String(100), nullable=False)
    password = db.Column(db.String(100), nullable=False)

    def __init__(self, first_name, last_name, email, date_of_birth, password):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.date_of_birth = date_of_birth
        self.password = password

    def save(self):
        db.session.add(self)
        db.session.commit()

    @staticmethod
    def get_all():
        return User.query.all()

weeks/08_week/mvc/app/controllers/user_controller.py
from flask import Blueprint, request, redirect, url_for
from views import user_view
from models.user_model import User

user_bp = Blueprint('user', __name__)

@user_bp.route('/')
def usuarios():
    users = User.get_all()
    return user_view.usuarios(users)

@user_bp.route('/users', methods=['GET', 'POST'])
def registro():
    if request.method == 'POST':
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        email = request.form['email']
        date_of_birth = request.form['date_of_birth']
        password = request.form['password']
        user = User(first_name, last_name, email, date_of_birth, password) #
        user.save()
        return redirect(url_for('user.usuarios'))
    return user_view.registro()

weeks/08_week/mvc/app/views/user_view.py
from flask import render_template


def usuarios(users):
    return render_template("usuarios.html", users=users)


def registro():
    return render_template("registro.html")

weeks/08_week/mvc/app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>MVC</title>
</head>
<body>
    <h1>MVC</h1>
    <nav>
        <a href="{{ url_for('user.registro') }}">Registrar Usuario</a> |
        <a href="{{ url_for('user.usuarios') }}">Lista de Usuarios</a>
    </nav>
    <div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

weeks/08_week/mvc/app/templates/registro.html
{% extends 'base.html' %}

{% block content %}
<h2>Registrar Usuario</h2>
<form method="post">
    <label for="first_name">Nombre:</label>
    <input type="text" id="first_name" name="first_name" required><br>

    <label for="last_name">Apellido:</label>
    <input type="text" id="last_name" name="last_name" required><br>

    <label for="gemail">Correo electrónico:</label>
    <input type="email" id="email" name="email" required><br>

    <label for="date_of_birth">Fecha de nacimiento:</label>
    <input type="date" id="date_of_birth" name="date_of_birth" required><br>

    <label for="password">Contraseña:</label>
    <input type="password" id="password" name="password" required><br>

    <input type="submit" value="Registrar">
</form>
{% endblock %}

weeks/08_week/mvc/app/templates/usuarios.html
{% extends 'base.html' %}

{% block content %}
<h2>Lista de Usuarios</h2>
<ul>
    {% for user in users %}
        <li>{{ user.first_name }} {{ user.last_name }} {{ user.email }} {{ user.date_of_birth }} {{ user.password }}</li>
    {% endfor %}
</ul>
{% endblock %}