weeks/08_week/mvc_crud/app/models/user_model.py
from database import db

class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    dob = db.Column(db.Date, nullable=False)

    def __init__(self, first_name, last_name, email, password, dob):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.password = password
        self.dob = dob

    def save(self):
        try:
            db.session.add(self)
            db.session.commit()
            return True
        except Exception as e:
            db.session.rollback()
            return False

    @staticmethod
    def get_all():
        return User.query.all()

    @staticmethod
    def get_by_id(id):
        return User.query.get(id)

    def update(self):
        try:
            db.session.commit()
            return True
        except Exception as e:
            db.session.rollback()
            return False

    def delete(self):
        try:
            db.session.delete(self)
            db.session.commit()
            return True
        except Exception as e:
            db.session.rollback()
            return False

weeks/08_week/mvc_crud/app/controllers/user_controller.py
from flask import Blueprint, request, redirect, url_for
from views import user_view
from models.user_model import User

user_bp = Blueprint("user", __name__)

@user_bp.route("/")
def index():
    return redirect(url_for("user.list_users"))


@user_bp.route("/users")
def list_users():
    users = User.get_all()
    return user_view.usuarios(users)

@user_bp.route("/users/create", methods=["GET", "POST"])
def create_user():
    if request.method == "POST":
        try:
            first_name = request.form["first_name"]
            last_name = request.form["last_name"]
            email = request.form["email"]
            password = request.form["password"]
            dob = request.form["dob"]

            user = User(first_name, last_name, email, password, dob)
            user.save()
            return redirect(url_for("user.list_users"))
        except Exception as e:
            return f"Error al crear usuario: {str(e)}"

    return user_view.registro()


@user_bp.route("/users/<int:id>/update", methods=["GET", "POST"])
def update_user(id):
    user = User.get_by_id(id)
    if not user:
        return "Usuario no encontrado", 404
    if request.method == "POST":
        try:
            first_name = request.form["first_name"]
            last_name = request.form["last_name"]
            email = request.form["email"]
            password = request.form["password"]
            dob = request.form["dob"]

            user.first_name = first_name
            user.last_name = last_name
            user.email = email
            user.password = password
            user.dob = dob
            user.update()
            return redirect(url_for("user.list_users"))
        except Exception as e:
            return f"Error al actualizar usuario: {str(e)}"
    return user_view.actualizar(user)


@user_bp.route("/users/<int:id>/delete")
def delete_user(id):
    user = User.get_by_id(id)
    if not user:
        return "Usuario no encontrado", 404
    try:
        user.delete()
        return redirect(url_for("user.list_users"))
    except Exception as e:
        return f"Error al eliminar usuario: {str(e)}"

weeks/08_week/mvc_crud/app/views/user_view.py
# render_template() es una función de Flask
# que renderiza un template de Jinja2.
from flask import render_template


# La función `usuarios` recibe una lista de
# usuarios y renderiza el template `usuarios.html`
def usuarios(users):
    return render_template("usuarios.html", users=users, title="Lista de usuarios")


def registro():
    return render_template("registro.html", title="Registro de usuarios")

def actualizar(user):
    return render_template("actualizar.html", title="Actualizar usuario", user=user)

weeks/08_week/mvc_crud/app/templates/actualizar.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Actualizar Usuario</h2>

<form method="post">
    <div class="field">
        <label for="first_name">Nombre:</label>
        <div class="control">
            <input type="text" id="first_name" name="first_name" required class="input" value="{{ user.first_name }}">
        </div>
    </div>
    <div class="field">
        <label for="last_name">Apellido:</label>
        <div class="control">
            <input type="text" id="last_name" name="last_name" required class="input" value="{{ user.last_name }}">
        </div>
    </div>
    <div class="field">
        <label for="email">Correo Electrónico:</label>
        <div class="control">
            <input type="email" id="email" name="email" required class="input" value="{{ user.email }}">
        </div>
    </div>
    <div class="field">
        <label for="date_of_birth">Fecha de Nacimiento:</label>
        <div class="control">
            <input type="date" id="date_of_birth" name="date_of_birth" class="input" value="{{ user.date_of_birth }}">
        </div>
    </div>
    <input type="submit" value="Actualizar" class="button is-primary">
</form>
{% endblock %}

weeks/08_week/mvc_crud/app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <title>{{title}}</title>
</head>
<body>
    <h1 class="title">MVC</h1>
    <nav  class="breadcrumb" aria-label="breadcrumbs" >
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="/">
                    {{ title.upper() }}
                </a>
                <a class="navbar-item" href="{{ url_for('user.create_user') }}">
                    Registrar Usuario
                </a>
                <a class="navbar-item" href="{{ url_for('user.list_users') }}">
                    Lista de Usuarios
                </a>
            </div>
        </div>
    </nav>
    <div class="columns is-mobile is-centered">
        <div class="column is-half">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

weeks/08_week/mvc_crud/app/templates/registro.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Registrar Usuario</h2>
<form method="post">
    <div class="field">
        <label for="first_name">Nombre:</label>
        <div class="control">
            <input type="text" id="first_name" name="first_name" required class="input">
        </div>
    </div>
    <div class="field">
        <label for="last_name">Apellido:</label>
        <div class="control">
            <input type="text" id="last_name" name="last_name" required class="input">
        </div>
    </div>
    <div class="field">
        <label for="email">Email:</label>
        <div class="control">
            <input type="email" id="email" name="email" required class="input">
        </div>
    </div>
    <div class="field">
        <label for="password">Contraseña:</label>
        <div class="control">
            <input type="password" id="password" name="password" required class="input">
        </div>
    </div>
    <div class="field">
        <label for="dob">Fecha de Nacimiento:</label>
        <div class="control">
            <input type="date" id="dob" name="dob" required class="input">
        </div>
    </div>
    <input type="submit" value="Registrar" class="button is-primary">
</form>
{% endblock %}

weeks/08_week/mvc_crud/app/templates/usuarios.html
{% extends 'base.html' %}

{% block content %}
<h2 class="subtitle is-2">Lista de Usuarios</h2>
    <div class="columns is-multiline">
        {% for user in users %}
            <div class="column is-one-third">
                <div class="card">
                    <div class="card-content">
                        <div class="content">
                            <p><strong>Nombre: {{ user.first_name }} </strong></p>
                            <p><strong>Apellido: {{ user.last_name }}</strong></p>
                            <div class="buttons">
                                <a href="{{ url_for('user.update_user', id=user.id) }}" 
                                class="button is-info">Editar</a>
                                <a href="{{ url_for('user.delete_user', id=user.id) }}" 
                                class="button is-danger">Eliminar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}